### ISSUE TITLE
[Grid] element selection does not get updated after deletion

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#1521]
**Steps to reproduce**

- Login as admin
- Open an asset folder
- Switch to the list view
- Select 4 objects
- Delete one of those objects

**Actual behaviour**
- Selector still shows 4 objects

![Image](https://github.com/user-attachments/assets/6123eecc-69c8-4794-8f14-0fab3bad36af)

**Expected behaviour**

- Selector should be updated to show 3 objects

**Environment**

- Playground
- Windows
- Google Chrome

**Comment by markus-moser** [comment]
should be fixed

**Comment by heigpa** [comment]
Still the same problem.

<img width="1348" height="911" alt="Image" src="https://github.com/user-attachments/assets/b63a47fa-6a2b-4a6d-a4a3-3712fd615577" />

**Comment by heigpa** [comment]
looks good now. thx
