### ISSUE TITLE
Folder deletion got stuck

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#1878]
**Steps to reproduce**

- Login as admin
- Create an asset folder called 'test'
- Upload all of those images (https://github.com/pimcore/studio-e2e-tests/tree/main/assets)
- Delete the folder
- Create another asset folder called 'test'
- Upload all of those images (https://github.com/pimcore/studio-e2e-tests/tree/main/assets)
- Delete the folder

**Actual behaviour**
- Sometimes the deletion gets stuck after the first deletion
- It always gets stuck after the second deletion
- Other jobs like asset zip download are than blocked as well

<img width="632" height="302" alt="Image" src="https://github.com/user-attachments/assets/6732beb7-4935-46b9-b2c3-5935188f2373" />

**Expected behaviour**
- Folder gets deleted
- No jobs get blocked

**Environment**

- Studio Nightly
- Windows
- Google Chrome

**Comment by markus-moser** [comment]
I guess this was fixed with this:
https://github.com/pimcore/studio-ui-bundle/pull/2092

**Comment by heigpa** [comment]
I still have the same issue. After 2 minutes i reloaded the browse and the objects still have been there.

<img width="1880" height="993" alt="Image" src="https://github.com/user-attachments/assets/deba8b73-4799-41b4-908b-1039e14ed95a" />

**Comment by ValeriaMaltseva** [comment]
@heigpa @markus-moser 
Looks like this bug - https://github.com/pimcore/studio-ui-bundle/issues/1729#issuecomment-3338791920 - is related to current one.

**Comment by markus-moser** [comment]
@heigpa I fixed some problems regarding re-connection of Mercure if the connection gets lost (https://github.com/pimcore/studio-ui-bundle/pull/2493). Hopefully this solves the problem now.

**Comment by heigpa** [comment]
looks good now. thx
