### ISSUE TITLE
[Bug] batch edit does not work

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#648]
**Steps to reproduce**

- Login as admin
- Open a folder 
- Switch to the list view
- Mark some assets
- Start a batch editing process
- Edit 'Title' and 'Author'

**Actual behaviour**
![Image](https://github.com/user-attachments/assets/ab21e064-1ae9-4ff1-b362-87aed65bef15)
![Image](https://github.com/user-attachments/assets/4ce7b75a-1502-4f1d-916c-ec50bcbe10b6)

- Batch edit did not work

**Expected behaviour**

- Values should be applied to the marked assets

**Environment**

- Nightly build

**Comment by markus-moser** [comment]
@xIrusux Please close this issue as soon as the functionallity is finalized so that @heigpa can retest it, thx.

**Comment by xIrusux** [comment]
Update on the issue: 
After some looking into this it turned out that there was a backend problem with how we were handling default metadata. 
"Title" is part of the default metadata. 
predefined metadata has already functioned i.e. "Author", "Source" etc. 

This problem has now been fixed. 

Taking a closer look has also pointed out that the "refresh" is happening to early in some cases which has to do with the job engine. 
This is something I am currently still looking into.

**Comment by xIrusux** [comment]
the refresh problem has been fixed @heigpa -> this one is ready to test again :) 
I will close the issue as per markus comment

**Comment by heigpa** [comment]
For me it still does not work on the nightly:

![Image](https://github.com/user-attachments/assets/c74d6a5c-d435-4bce-8a80-7d93fd2d9a36)

![Image](https://github.com/user-attachments/assets/874f0969-8f18-4205-9228-eb136657be26)

**Comment by ValeriaMaltseva** [comment]
@heigpa Check, please, one more time.

**Comment by heigpa** [comment]
works now. thx
